package com.cpan252.tekkenreborn.model;

import java.time.LocalDate;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
//jakarta == javax
// By using the @Table annotation, we are telling Spring Data to map the table
// name to the table
/**
 * @Entity is a JPA annotation to make this object ready for storage in a JPA based data store. (required)
 * @Id is a JPA annotation to make this field the primary key for this object. (required)
 * @GeneratedValue is a JPA annotation to make this field auto-generated by the JPA provider (required).
 * We also have to have no argument constructor for object to be created by JPA.
 */
@Entity
public class Item {
    // Using JPA, we have to provide correct @Id annotation and use @GeneratedValue
    // to auto-generate the id, see the imports
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Brand brand;

    @Column(nullable = false)
    private int yearOfCreation;

    @Column(nullable = false)
    private double price;

    @Builder.Default
    private LocalDate createdAt = LocalDate.now();
    
    public enum Brand  {
        BALENCIAGA,
        STONE_ISLAND,
        DIOR;

        private String title;

        private Brand(String title) {
            this.title = title;
        }

        Brand() {

        }

        public String getTitle() {
            return title;
        }
    }
}
